'use client'

import { useCallback, useEffect, useMemo, useState } from 'react'
import { CheckCircle2, Copy, Download, KeyRound, Loader2, RefreshCw, Search, Send, Settings2, ShieldCheck, Sparkles, Star, TrendingDown, X } from 'lucide-react'

type Product = { id: string; title: string; imageUrl: string; originalPrice: number; dealPrice: number; rating: number; stock: number; affiliateUrl: string; caption: string }
type Credentials = { appId: string; secretKey: string; affiliateId: string }
const emptyCredentials: Credentials = { appId: '18336041241', secretKey: '', affiliateId: '18336041241' }
const fallbackProducts: Product[] = [
  { id: '1', title: 'Fone Bluetooth Pro com cancelamento de ruído', imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=700&q=85', originalPrice: 189.9, dealPrice: 79.9, rating: 4.9, stock: 83, affiliateUrl: 'https://shope.ee/achadinho-fone', caption: 'OFERTA RELÂMPAGO\n\nFone Bluetooth Pro por apenas R$ 79,90.\nDe R$ 189,90 por R$ 79,90 — 58% OFF.\n\nConfira: https://shope.ee/achadinho-fone' },
  { id: '2', title: 'Organizador inteligente para cozinha', imageUrl: 'https://images.unsplash.com/photo-1556911220-bff31c812dba?auto=format&fit=crop&w=700&q=85', originalPrice: 119.9, dealPrice: 49.9, rating: 4.8, stock: 126, affiliateUrl: 'https://shope.ee/achadinho-organizador', caption: 'ACHADINHO DO DIA\n\nOrganizador inteligente por R$ 49,90.\nEconomize 58% e deixe tudo no lugar.\n\nLink: https://shope.ee/achadinho-organizador' },
  { id: '3', title: 'Tênis casual confortável unissex', imageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=700&q=85', originalPrice: 249.9, dealPrice: 99.9, rating: 4.7, stock: 41, affiliateUrl: 'https://shope.ee/achadinho-tenis', caption: 'PREÇO IMPERDÍVEL\n\nTênis casual por R$ 99,90.\nDe R$ 249,90 por R$ 99,90 — 60% OFF.\n\nGaranta: https://shope.ee/achadinho-tenis' },
]

export function AdminDashboard() {
  const [products, setProducts] = useState<Product[]>(fallbackProducts)
  const [credentials, setCredentials] = useState<Credentials>(emptyCredentials)
  const [showSettings, setShowSettings] = useState(false)
  const [apiEnabled, setApiEnabled] = useState(false)
  const [releasedIds, setReleasedIds] = useState<string[]>([])
  const [loading, setLoading] = useState(false)
  const [notice, setNotice] = useState('')
  const [query, setQuery] = useState('')
  const [refreshKey, setRefreshKey] = useState(0)
  const [seenIds, setSeenIds] = useState<string[]>(fallbackProducts.map((product) => product.id))

  useEffect(() => {
    const saved = window.localStorage.getItem('shopee-affiliate-credentials')
    const enabled = window.localStorage.getItem('shopee-affiliate-api-enabled') === 'true'
    if (saved) setCredentials(JSON.parse(saved))
    setApiEnabled(enabled)
  }, [])
  const fetchDeals = useCallback(async (requestedRefreshKey = refreshKey) => {
    setLoading(true)
    try { const response = await fetch('/api/shopee-live-deals', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ credentials, refreshKey: requestedRefreshKey }) }); const data = await response.json(); const freshProducts = (data.products || []).filter((product: Product) => !seenIds.includes(product.id)); if (response.ok && freshProducts.length) { setProducts(freshProducts); setSeenIds((ids) => [...ids, ...freshProducts.map((product: Product) => product.id)]); setNotice(`${freshProducts.length} ofertas novas encontradas.`) } else if (response.ok && data.products?.length) { setNotice('A Shopee retornou ofertas já exibidas. Clique novamente para buscar outra página.') } else setNotice(data.error || 'Configure suas credenciais para buscar ao vivo.') } catch { setNotice('Não foi possível buscar ofertas agora. Tente novamente.') } finally { setLoading(false) }
  }, [credentials, refreshKey, seenIds])
  const saveCredentials = () => { window.localStorage.setItem('shopee-affiliate-credentials', JSON.stringify(credentials)); window.localStorage.setItem('shopee-affiliate-api-enabled', String(apiEnabled)); setShowSettings(false); setNotice(apiEnabled ? 'API Shopee ativada neste navegador.' : 'Configurações salvas.'); if (apiEnabled) fetchDeals() }
  const releaseOffer = async (product: Product) => { setLoading(true); try { const response = await fetch('/api/send-telegram', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ caption: product.caption, imageUrl: product.imageUrl }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Falha no Telegram'); await copy(product.caption); setReleasedIds((ids) => ids.includes(product.id) ? ids : [...ids, product.id]); setNotice('Oferta enviada para o canal do Telegram e texto copiado.'); } catch (error) { setNotice(error instanceof Error ? error.message : 'Não foi possível enviar para o Telegram.'); } finally { setLoading(false) } }
  const filtered = useMemo(() => products.filter((p) => p.title.toLowerCase().includes(query.toLowerCase())), [products, query])
  const copy = async (text: string) => { await navigator.clipboard.writeText(text); setNotice('Texto copiado para a área de transferência.') }
  const money = (value: number) => value.toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' })
  const discount = (p: Product) => Math.round((1 - p.dealPrice / p.originalPrice) * 100)
  return <main className="min-h-screen bg-background text-foreground">
    <header className="sticky top-0 z-20 border-b border-border/70 bg-background/90 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between gap-4 px-5 py-4 sm:px-8"><div className="flex items-center gap-3"><div className="flex size-10 items-center justify-center rounded-2xl bg-primary text-primary-foreground"><Sparkles size={19} /></div><div><p className="font-semibold tracking-tight">Shopee <span className="text-primary">Achadinhos</span></p><p className="text-xs text-muted-foreground">Offer generator ao vivo</p></div></div><div className="flex items-center gap-2"><div className="hidden items-center gap-2 rounded-full border border-emerald-500/20 bg-emerald-500/10 px-3 py-2 text-xs font-medium text-emerald-600 sm:flex"><span className="size-1.5 rounded-full bg-emerald-500" /> API online</div><button onClick={() => setShowSettings(true)} className="flex size-10 items-center justify-center rounded-xl border border-border bg-card hover:bg-muted" aria-label="Abrir configurações"><Settings2 size={18} /></button></div></div></header>
    <div className="mx-auto max-w-7xl px-5 py-8 sm:px-8 lg:py-12"><section className="mb-8 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="mb-3 flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.2em] text-primary"><span className="size-2 rounded-full bg-primary" /> monitoramento ativo</p><h1 className="max-w-2xl text-balance text-3xl font-semibold tracking-[-0.04em] sm:text-5xl">Encontre ofertas que <span className="text-primary">vendem sozinhas.</span></h1><p className="mt-4 max-w-xl text-pretty leading-6 text-muted-foreground">Busque achadinhos em alta, gere sua copy e compartilhe onde sua audiência está.</p></div><div className="flex items-center gap-3"><button onClick={() => { const nextRefreshKey = refreshKey + 1; setRefreshKey(nextRefreshKey); fetchDeals(nextRefreshKey) }} disabled={loading} className="flex h-14 items-center gap-2 rounded-2xl bg-primary px-5 font-semibold text-primary-foreground shadow-lg shadow-primary/20 hover:opacity-90 disabled:opacity-60"><RefreshCw className={loading ? 'animate-spin' : ''} size={18} /> <span>Buscar novas ofertas</span></button><button onClick={() => filtered[0] && releaseOffer(filtered[0])} disabled={!filtered[0]} className="flex h-14 items-center gap-2 rounded-2xl border border-primary/30 bg-primary/10 px-5 font-semibold text-primary hover:bg-primary/20 disabled:opacity-50"><Send size={18} /> <span className="hidden sm:inline">Soltar oferta</span></button></div></section>
      <section className="mb-8 grid gap-3 sm:grid-cols-3"><Metric icon={<TrendingDown size={18} />} label="Ofertas encontradas" value={String(products.length)} /><Metric icon={<Sparkles size={18} />} label="Desconto médio" value={`${products.length ? Math.round(products.reduce((a, p) => a + discount(p), 0) / products.length) : 0}%`} /><Metric icon={<ShieldCheck size={18} />} label="Última busca" value="Ao vivo" /></section>
      {notice && <div className="mb-6 flex items-center justify-between rounded-2xl border border-primary/20 bg-primary/5 px-4 py-3 text-sm text-primary"><span>{notice}</span><button onClick={() => setNotice('')} aria-label="Fechar aviso"><X size={16} /></button></div>}
      <div className="mb-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><h2 className="text-xl font-semibold tracking-tight">Ofertas em alta</h2><p className="mt-1 text-sm text-muted-foreground">Links afiliados prontos para compartilhar</p></div><div className="relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground" size={17} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Filtrar ofertas..." className="h-11 w-full rounded-xl border border-input bg-card pl-10 pr-4 text-sm outline-none ring-primary focus:ring-2 sm:w-64" /></div></div>
      <div className="grid gap-5 lg:grid-cols-2">{filtered.map((product) => <ProductCard key={product.id} product={product} discount={discount(product)} money={money} onCopy={copy} onRelease={releaseOffer} released={releasedIds.includes(product.id)} />)}</div>
    </div>
    {showSettings && <div className="fixed inset-0 z-40 flex items-end justify-center bg-foreground/30 p-0 backdrop-blur-sm sm:items-center sm:p-5"><section className="w-full max-w-lg rounded-t-3xl border border-border bg-card p-6 shadow-2xl sm:rounded-3xl"><div className="mb-6 flex items-start justify-between"><div><h2 className="text-xl font-semibold">Credenciais Shopee</h2><p className="mt-1 text-sm text-muted-foreground">Salvas apenas neste navegador.</p></div><button onClick={() => setShowSettings(false)} className="rounded-lg p-2 hover:bg-muted" aria-label="Fechar configurações"><X size={18} /></button></div><div className="mb-5 flex gap-3 rounded-2xl bg-muted/60 p-4 text-sm"><KeyRound className="mt-0.5 shrink-0 text-primary" size={17} /><p className="text-muted-foreground">Nunca compartilhamos sua Secret Key com o cliente. Ela é enviada somente para a função serverless assinada.</p></div><div className="grid gap-4">{([['appId', 'App ID'], ['secretKey', 'Secret Key'], ['affiliateId', 'Affiliate ID']] as const).map(([key, label]) => <label key={key} className="grid gap-2 text-sm font-medium">{label}<input type={key === 'secretKey' ? 'password' : 'text'} value={credentials[key]} onChange={(e) => setCredentials({ ...credentials, [key]: e.target.value })} className="h-11 rounded-xl border border-input bg-background px-3 outline-none ring-primary focus:ring-2" placeholder={label} /></label>)}</div><label className="mt-5 flex cursor-pointer items-center justify-between rounded-2xl border border-border bg-muted/40 p-4"><span><span className="block text-sm font-semibold">Ativar API Shopee</span><span className="mt-1 block text-xs text-muted-foreground">Usar estas credenciais nas buscas ao vivo.</span></span><input type="checkbox" checked={apiEnabled} onChange={(e) => setApiEnabled(e.target.checked)} className="size-5 accent-primary" /></label><button onClick={saveCredentials} className="mt-6 h-12 w-full rounded-xl bg-primary font-semibold text-primary-foreground">{apiEnabled ? 'Ativar e buscar ofertas' : 'Salvar configurações'}</button></section></div>}
  </main>
}
function Metric({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) { return <div className="flex items-center gap-3 rounded-2xl border border-border bg-card p-4"><span className="flex size-9 items-center justify-center rounded-xl bg-primary/10 text-primary">{icon}</span><div><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 font-semibold">{value}</p></div></div> }
function ProductCard({ product, discount, money, onCopy, onRelease, released }: { product: Product; discount: number; money: (v: number) => string; onCopy: (v: string) => void; onRelease: (product: Product) => void; released: boolean }) { return <article className="overflow-hidden rounded-3xl border border-border bg-card shadow-sm transition hover:-translate-y-0.5 hover:shadow-lg"><div className="flex flex-col sm:flex-row"><div className="relative aspect-[1.15] w-full shrink-0 overflow-hidden bg-muted sm:aspect-square sm:w-44"><img src={product.imageUrl} alt={product.title} className="size-full object-cover" /><span className="absolute left-3 top-3 rounded-lg bg-primary px-2.5 py-1 text-xs font-bold text-primary-foreground">-{discount}%</span></div><div className="flex min-w-0 flex-1 flex-col p-5"><div className="flex items-start justify-between gap-3"><h3 className="line-clamp-2 font-semibold leading-5">{product.title}</h3><span className="flex shrink-0 items-center gap-1 text-xs font-medium text-amber-600"><Star size={13} fill="currentColor" /> {product.rating}</span></div><div className="mt-4 flex items-end gap-2"><span className="text-2xl font-bold tracking-tight">{money(product.dealPrice)}</span><span className="text-sm text-muted-foreground line-through">{money(product.originalPrice)}</span></div><p className="mt-1 text-xs text-muted-foreground">{product.stock} unidades disponíveis</p><textarea readOnly value={product.caption} className="mt-4 min-h-24 resize-none rounded-xl border border-border bg-muted/40 p-3 text-xs leading-5 text-muted-foreground outline-none" /><div className="mt-3 flex gap-2"><button onClick={() => onRelease(product)} className="flex h-10 flex-1 items-center justify-center gap-2 rounded-xl bg-primary text-sm font-semibold text-primary-foreground hover:opacity-90">{released ? <CheckCircle2 size={15} /> : <Send size={15} />} {released ? 'Oferta solta' : 'Soltar oferta'}</button><button onClick={() => onCopy(product.caption)} className="flex h-10 items-center justify-center gap-2 rounded-xl border border-border px-3 text-sm font-medium hover:bg-muted"><Copy size={15} /><span className="sr-only">Copiar texto</span></button><a href={product.imageUrl} download={`achadinho-${product.id}.jpg`} className="flex h-10 items-center justify-center gap-2 rounded-xl border border-border px-3 text-sm font-medium hover:bg-muted" aria-label="Baixar imagem"><Download size={15} /></a></div></div></div></article> }
